<?php

namespace App\Http\Requests;

use App\Models\User;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;
use Illuminate\Validation\Rules\File;

class InviteSubmitRequest extends FormRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\Rule|array|string>
     */
    public function rules(): array
    {
        return [
            'full_name' => ['required', 'max:255'],
            'work_place' => ['required', 'max:255'],
            'phone_number' => ['required', 'max:255'],
            'email' => ['required', 'email', 'max:255'],
            'passport' => [
                Rule::requiredIf($this->form_of_attendance === \App\Enums\FormOfAttendance::Offline->value),
                'file',
                File::types(['pdf', 'png', 'jpg', 'jpeg'])
            ],
            'diploma' => [
                Rule::requiredIf($this->form_of_attendance === \App\Enums\FormOfAttendance::Offline->value),
                'file',
                File::types(['pdf', 'png', 'jpg', 'jpeg'])
            ],
            'form_of_attendance' => ['required', Rule::in(array_keys(\App\Enums\FormOfAttendance::getDropdownOptions()))],
        ];
    }

    public function messages(): array
    {
        $messages = parent::messages(); // TODO: Change the autogenerated stub
        $messages['passport.required'] = __('Passport is required for offline attendants in order to get a certificate.');
        $messages['diploma.required'] = __('Diploma is required for offline attendants in order to get a certificate.');
        return $messages;
    }
}
